import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen py-2">
      <Head>
        <title>Tone Indicators</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full flex-1 px-20 text-center">
      <h1 className="text-6xl font-bold">
          Welcome to{' '}
          <a className="text-blue-600" href="https://toneindicators.carrd.co/#masterlist">
            Tone Indicators!
          </a>
        </h1>

        <label className="block text-left max-w-4xl mt-12 sm:w-full">
          <h3 className="text-2xl font-bold">Tell me what you're confused about &darr;</h3>
          <textarea className="form-textarea p-6 mt-6 block w-full border rounded-xl hover:text-blue-600 focus:text-blue-600" placeholder="Enter some long form content."></textarea>
        </label>

      </main>

      <footer className="flex items-center justify-center w-full h-24 border-t">
        <a
          className="flex items-center justify-center"
          href="https://mit.edu"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by AI@MIT
        </a>
      </footer>
    </div>
  )
}

export default Home
